//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Chat_CancelStreaming {
            get {
                return ResourceManager.GetString("Chat_CancelStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Step Debugging.
        /// </summary>
        public static string Chat_DisableStepDebugging {
            get {
                return ResourceManager.GetString("Chat_DisableStepDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Step Debugging.
        /// </summary>
        public static string Chat_EnableStepDebugging {
            get {
                return ResourceManager.GetString("Chat_EnableStepDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load chat history..
        /// </summary>
        public static string Chat_Error_LoadChatHistory {
            get {
                return ResourceManager.GetString("Chat_Error_LoadChatHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process edited message..
        /// </summary>
        public static string Chat_Error_ProcessEditedMessage {
            get {
                return ResourceManager.GetString("Chat_Error_ProcessEditedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error regenerating response: {0}.
        /// </summary>
        public static string Chat_Error_RegenerateResponse {
            get {
                return ResourceManager.GetString("Chat_Error_RegenerateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to regenerate responses..
        /// </summary>
        public static string Chat_Error_RegenerateResponses {
            get {
                return ResourceManager.GetString("Chat_Error_RegenerateResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Audio.
        /// </summary>
        public static string Chat_PlayAudio {
            get {
                return ResourceManager.GetString("Chat_PlayAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00.
        /// </summary>
        public static string Chat_RecordingInitialTime {
            get {
                return ResourceManager.GetString("Chat_RecordingInitialTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording time: {0:mm\\:ss}.
        /// </summary>
        public static string Chat_RecordingTime {
            get {
                return ResourceManager.GetString("Chat_RecordingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording voice message....
        /// </summary>
        public static string Chat_RecordingVoiceMessage {
            get {
                return ResourceManager.GetString("Chat_RecordingVoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Chat_Send {
            get {
                return ResourceManager.GetString("Chat_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Debugging.
        /// </summary>
        public static string Chat_StepDebugging {
            get {
                return ResourceManager.GetString("Chat_StepDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step debugging is active. Click Step Next to send the next message..
        /// </summary>
        public static string Chat_StepDebuggingActive {
            get {
                return ResourceManager.GetString("Chat_StepDebuggingActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Next Message (F11).
        /// </summary>
        public static string Chat_StepNext {
            get {
                return ResourceManager.GetString("Chat_StepNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Step Next (F11) to continue.
        /// </summary>
        public static string Chat_WaitingForStep {
            get {
                return ResourceManager.GetString("Chat_WaitingForStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string Chat_StopRecordingButton {
            get {
                return ResourceManager.GetString("Chat_StopRecordingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Chat_Tools {
            get {
                return ResourceManager.GetString("Chat_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a message....
        /// </summary>
        public static string Chat_TypeMessage {
            get {
                return ResourceManager.GetString("Chat_TypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string Chat_UploadFile {
            get {
                return ResourceManager.GetString("Chat_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Recording.
        /// </summary>
        public static string Chat_VoiceRecordingDescription {
            get {
                return ResourceManager.GetString("Chat_VoiceRecordingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool function name conflicts detected for &apos;{0}&apos; in module &apos;{1}&apos;. Please rename conflicting functions or enable auto-resolution in settings..
        /// </summary>
        public static string Error_ToolNameConflictDetected {
            get {
                return ResourceManager.GetString("Error_ToolNameConflictDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s help you get set up to start. Follow these simple steps:.
        /// </summary>
        public static string Home_GettingStarted_Description {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. First, configure an.
        /// </summary>
        public static string Home_GettingStarted_Step1 {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Provider.
        /// </summary>
        public static string Home_GettingStarted_Step1_Link {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Step1_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to connect to your preferred AI service.
        /// </summary>
        public static string Home_GettingStarted_Step1_Suffix {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Step1_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Then, create a.
        /// </summary>
        public static string Home_GettingStarted_Step2 {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Home_GettingStarted_Step2_Link {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Step2_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with the personality and capabilities you want.
        /// </summary>
        public static string Home_GettingStarted_Step2_Suffix {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Step2_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Optionally, add.
        /// </summary>
        public static string Home_GettingStarted_Step3 {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Home_GettingStarted_Step3_Link {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Step3_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to give your AI agents special abilities, or simply start chatting right away!.
        /// </summary>
        public static string Home_GettingStarted_Step3_Suffix {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Step3_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Dao Studio!.
        /// </summary>
        public static string Home_GettingStarted_Title {
            get {
                return ResourceManager.GetString("Home_GettingStarted_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chat history available. Click on a person to get started..
        /// </summary>
        public static string Home_NoSessionsAvailable {
            get {
                return ResourceManager.GetString("Home_NoSessionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on person to start chat.
        /// </summary>
        public static string Home_Person {
            get {
                return ResourceManager.GetString("Home_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Home_Sessions {
            get {
                return ResourceManager.GetString("Home_Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dao Studio.
        /// </summary>
        public static string MainWindow_PaneTitle {
            get {
                return ResourceManager.GetString("MainWindow_PaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dao Studio.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavItem_Home {
            get {
                return ResourceManager.GetString("NavItem_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string NavItem_People {
            get {
                return ResourceManager.GetString("NavItem_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavItem_Settings {
            get {
                return ResourceManager.GetString("NavItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string NavItem_Tools {
            get {
                return ResourceManager.GetString("NavItem_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Content.
        /// </summary>
        public static string People_AdditionalContent {
            get {
                return ResourceManager.GetString("People_AdditionalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON object with additional content properties. Example shown in the watermark..
        /// </summary>
        public static string People_AdditionalContentTooltip {
            get {
                return ResourceManager.GetString("People_AdditionalContentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;provider&quot;: {
        ///        &quot;order&quot;: [
        ///            &quot;openai&quot;,
        ///            &quot;together&quot;
        ///        ],
        ///        &quot;allow_fallbacks&quot;: false,
        ///        &quot;data_collection&quot;: &quot;deny&quot;,
        ///        &quot;ignore&quot;: [
        ///            &quot;xyz&quot;
        ///        ]
        ///    }
        ///}.
        /// </summary>
        public static string People_AdditionalContentWatermark {
            get {
                return ResourceManager.GetString("People_AdditionalContentWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Person.
        /// </summary>
        public static string People_AddNewPerson {
            get {
                return ResourceManager.GetString("People_AddNewPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Person.
        /// </summary>
        public static string People_AddPerson {
            get {
                return ResourceManager.GetString("People_AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Catalogs.
        /// </summary>
        public static string People_AllCatalogs {
            get {
                return ResourceManager.GetString("People_AllCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available People.
        /// </summary>
        public static string People_AvailablePeople {
            get {
                return ResourceManager.GetString("People_AvailablePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string People_BasicInfo {
            get {
                return ResourceManager.GetString("People_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string People_CapabilitiesAndTools {
            get {
                return ResourceManager.GetString("People_CapabilitiesAndTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string People_Catalog {
            get {
                return ResourceManager.GetString("People_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Image.
        /// </summary>
        public static string People_ClearImage {
            get {
                return ResourceManager.GetString("People_ClearImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Person.
        /// </summary>
        public static string People_ConfirmDeletePerson {
            get {
                return ResourceManager.GetString("People_ConfirmDeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;? This action cannot be undone..
        /// </summary>
        public static string People_ConfirmDeletePersonMessage {
            get {
                return ResourceManager.GetString("People_ConfirmDeletePersonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Model.
        /// </summary>
        public static string People_CurrentModel {
            get {
                return ResourceManager.GetString("People_CurrentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string People_Description {
            get {
                return ResourceManager.GetString("People_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for creating sub tasks.
        /// </summary>
        public static string People_DescriptionTooltip {
            get {
                return ResourceManager.GetString("People_DescriptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance and behavior to others.
        /// </summary>
        public static string People_DescriptionWatermark {
            get {
                return ResourceManager.GetString("People_DescriptionWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string People_EditPersonTitleFormat {
            get {
                return ResourceManager.GetString("People_EditPersonTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Penalty.
        /// </summary>
        public static string People_FrequencyPenalty {
            get {
                return ResourceManager.GetString("People_FrequencyPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalizes tokens based on how frequently they appear in the text. Higher values reduce repetition. Range: -2.0 to 2.0.
        /// </summary>
        public static string People_FrequencyPenaltyTooltip {
            get {
                return ResourceManager.GetString("People_FrequencyPenaltyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., 0.5 (leave empty for model default).
        /// </summary>
        public static string People_FrequencyPenaltyWatermark {
            get {
                return ResourceManager.GetString("People_FrequencyPenaltyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Headers.
        /// </summary>
        public static string People_HttpHeaders {
            get {
                return ResourceManager.GetString("People_HttpHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP headers as key-value pairs, one per line. Example: &quot;HTTP-Referer: https://example.com&quot;.
        /// </summary>
        public static string People_HttpHeadersTooltip {
            get {
                return ResourceManager.GetString("People_HttpHeadersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP-Referer: &lt;YOUR_SITE_URL&gt;
        ///X-Title: &lt;YOUR_SITE_NAME&gt;.
        /// </summary>
        public static string People_HttpHeadersWatermark {
            get {
                return ResourceManager.GetString("People_HttpHeadersWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM Parameters.
        /// </summary>
        public static string People_LLMParameters {
            get {
                return ResourceManager.GetString("People_LLMParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Selection.
        /// </summary>
        public static string People_ModelSelection {
            get {
                return ResourceManager.GetString("People_ModelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string People_Name {
            get {
                return ResourceManager.GetString("People_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name is required..
        /// </summary>
        public static string People_NameRequired {
            get {
                return ResourceManager.GetString("People_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a user-friendly name for the person.
        /// </summary>
        public static string People_NameWatermark {
            get {
                return ResourceManager.GetString("People_NameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first person to start using them with this application.
        /// </summary>
        public static string People_NoPeopleDescription {
            get {
                return ResourceManager.GetString("People_NoPeopleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No People Configured.
        /// </summary>
        public static string People_NoPeopleTitle {
            get {
                return ResourceManager.GetString("People_NoPeopleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person ID is required..
        /// </summary>
        public static string People_PersonIdRequired {
            get {
                return ResourceManager.GetString("People_PersonIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence Penalty.
        /// </summary>
        public static string People_PresencePenalty {
            get {
                return ResourceManager.GetString("People_PresencePenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalizes tokens that have already appeared in the text. Higher values encourage the model to talk about new topics. Range: -2.0 to 2.0.
        /// </summary>
        public static string People_PresencePenaltyTooltip {
            get {
                return ResourceManager.GetString("People_PresencePenaltyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., 0.6 (leave empty for model default).
        /// </summary>
        public static string People_PresencePenaltyWatermark {
            get {
                return ResourceManager.GetString("People_PresencePenaltyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string People_Provider {
            get {
                return ResourceManager.GetString("People_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider and Model.
        /// </summary>
        public static string People_ProviderAndModel {
            get {
                return ResourceManager.GetString("People_ProviderAndModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider is required..
        /// </summary>
        public static string People_ProviderRequired {
            get {
                return ResourceManager.GetString("People_ProviderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must add at least one provider before adding people..
        /// </summary>
        public static string People_ProvidersRequired {
            get {
                return ResourceManager.GetString("People_ProvidersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Tools.
        /// </summary>
        public static string People_SelectedTools {
            get {
                return ResourceManager.GetString("People_SelectedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tools.
        /// </summary>
        public static string People_SelectTools {
            get {
                return ResourceManager.GetString("People_SelectTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string People_Temperature {
            get {
                return ResourceManager.GetString("People_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls randomness in responses. Higher values (e.g., 0.8) make output more creative, while lower values (e.g., 0.2) make it more focused and deterministic. Range: 0.0 to 2.0.
        /// </summary>
        public static string People_TemperatureTooltip {
            get {
                return ResourceManager.GetString("People_TemperatureTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., 0.7 (leave empty for model default).
        /// </summary>
        public static string People_TemperatureWatermark {
            get {
                return ResourceManager.GetString("People_TemperatureWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People_Title {
            get {
                return ResourceManager.GetString("People_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top K.
        /// </summary>
        public static string People_TopK {
            get {
                return ResourceManager.GetString("People_TopK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits sampling to the K most likely tokens. Lower values make responses more focused. Typical range: 1 to 100..
        /// </summary>
        public static string People_TopKTooltip {
            get {
                return ResourceManager.GetString("People_TopKTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., 40 (leave empty for model default).
        /// </summary>
        public static string People_TopKWatermark {
            get {
                return ResourceManager.GetString("People_TopKWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top P.
        /// </summary>
        public static string People_TopP {
            get {
                return ResourceManager.GetString("People_TopP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls diversity via nucleus sampling. Only tokens with cumulative probability up to top_p are considered. Range: 0.0 to 1.0. Lower values focus on more likely tokens..
        /// </summary>
        public static string People_TopPTooltip {
            get {
                return ResourceManager.GetString("People_TopPTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., 0.9 (leave empty for model default).
        /// </summary>
        public static string People_TopPWatermark {
            get {
                return ResourceManager.GetString("People_TopPWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string People_UploadImage {
            get {
                return ResourceManager.GetString("People_UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use all available tools.
        /// </summary>
        public static string People_UseAllTools {
            get {
                return ResourceManager.GetString("People_UseAllTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Provider.
        /// </summary>
        public static string Settings_AddProvider {
            get {
                return ResourceManager.GetString("Settings_AddProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Endpoint:.
        /// </summary>
        public static string Settings_ApiEndpoint {
            get {
                return ResourceManager.GetString("Settings_ApiEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        public static string Settings_ApiKey {
            get {
                return ResourceManager.GetString("Settings_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-resolve tool function name conflicts.
        /// </summary>
        public static string Settings_AutoResolveToolNameConflicts {
            get {
                return ResourceManager.GetString("Settings_AutoResolveToolNameConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When multiple tools have functions with the same name, automatically add prefixes to make them unique. If disabled, conflicts will trigger an error message..
        /// </summary>
        public static string Settings_AutoResolveToolNameConflictsDescription {
            get {
                return ResourceManager.GetString("Settings_AutoResolveToolNameConflictsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Settings_CancelButton {
            get {
                return ResourceManager.GetString("Settings_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Provider.
        /// </summary>
        public static string Settings_ConfirmDeleteProvider {
            get {
                return ResourceManager.GetString("Settings_ConfirmDeleteProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this provider?.
        /// </summary>
        public static string Settings_ConfirmDeleteProviderMessage {
            get {
                return ResourceManager.GetString("Settings_ConfirmDeleteProviderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Settings_Delete {
            get {
                return ResourceManager.GetString("Settings_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Settings_DeleteButton {
            get {
                return ResourceManager.GetString("Settings_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Provider Name.
        /// </summary>
        public static string Settings_EditProviderTitle {
            get {
                return ResourceManager.GetString("Settings_EditProviderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Settings_Error {
            get {
                return ResourceManager.GetString("Settings_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading People.
        /// </summary>
        public static string Settings_ErrorLoadingPeople {
            get {
                return ResourceManager.GetString("Settings_ErrorLoadingPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string Settings_ErrorOccurred {
            get {
                return ResourceManager.GetString("Settings_ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load people: {0}.
        /// </summary>
        public static string Settings_FailedLoadPeople {
            get {
                return ResourceManager.GetString("Settings_FailedLoadPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_GeneralTab {
            get {
                return ResourceManager.GetString("Settings_GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Providers.
        /// </summary>
        public static string Settings_LlmProviders {
            get {
                return ResourceManager.GetString("Settings_LlmProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading people list....
        /// </summary>
        public static string Settings_LoadingPeople {
            get {
                return ResourceManager.GetString("Settings_LoadingPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a provider to get started with Dao Studio.
        /// </summary>
        public static string Settings_NoProvidersDescription {
            get {
                return ResourceManager.GetString("Settings_NoProvidersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No providers configured.
        /// </summary>
        public static string Settings_NoProvidersTitle {
            get {
                return ResourceManager.GetString("Settings_NoProvidersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter provider name.
        /// </summary>
        public static string Settings_ProviderNameWatermark {
            get {
                return ResourceManager.GetString("Settings_ProviderNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the API providers you want to use with Dao Studio..
        /// </summary>
        public static string Settings_ProvidersDescription {
            get {
                return ResourceManager.GetString("Settings_ProvidersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Settings_SaveButton {
            get {
                return ResourceManager.GetString("Settings_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Directory:.
        /// </summary>
        public static string Settings_System_AppDirectory {
            get {
                return ResourceManager.GetString("Settings_System_AppDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalonia Version:.
        /// </summary>
        public static string Settings_System_AvaloniaVersion {
            get {
                return ResourceManager.GetString("Settings_System_AvaloniaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Configuration:.
        /// </summary>
        public static string Settings_System_BuildConfiguration {
            get {
                return ResourceManager.GetString("Settings_System_BuildConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Path:.
        /// </summary>
        public static string Settings_System_ExecutablePath {
            get {
                return ResourceManager.GetString("Settings_System_ExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Runtime:.
        /// </summary>
        public static string Settings_System_Framework {
            get {
                return ResourceManager.GetString("Settings_System_Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System:.
        /// </summary>
        public static string Settings_System_OS {
            get {
                return ResourceManager.GetString("Settings_System_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Architecture:.
        /// </summary>
        public static string Settings_System_OSArchitecture {
            get {
                return ResourceManager.GetString("Settings_System_OSArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Architecture:.
        /// </summary>
        public static string Settings_System_ProcessArchitecture {
            get {
                return ResourceManager.GetString("Settings_System_ProcessArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Version:.
        /// </summary>
        public static string Settings_System_RuntimeVersion {
            get {
                return ResourceManager.GetString("Settings_System_RuntimeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        public static string Settings_SystemInfo_Title {
            get {
                return ResourceManager.GetString("Settings_SystemInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        public static string Settings_Theme_System {
            get {
                return ResourceManager.GetString("Settings_Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Name Conflicts.
        /// </summary>
        public static string Settings_ToolConflictResolution {
            get {
                return ResourceManager.GetString("Settings_ToolConflictResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Version:.
        /// </summary>
        public static string Settings_Version_Assembly {
            get {
                return ResourceManager.GetString("Settings_Version_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Time:.
        /// </summary>
        public static string Settings_Version_BuildTime {
            get {
                return ResourceManager.GetString("Settings_Version_BuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string Settings_Version_CheckForUpdates {
            get {
                return ResourceManager.GetString("Settings_Version_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string Settings_Version_CheckingForUpdates {
            get {
                return ResourceManager.GetString("Settings_Version_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version:.
        /// </summary>
        public static string Settings_Version_CurrentVersion {
            get {
                return ResourceManager.GetString("Settings_Version_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version:.
        /// </summary>
        public static string Settings_Version_File {
            get {
                return ResourceManager.GetString("Settings_Version_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Branch:.
        /// </summary>
        public static string Settings_Version_GitBranch {
            get {
                return ResourceManager.GetString("Settings_Version_GitBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git Commit:.
        /// </summary>
        public static string Settings_Version_GitCommit {
            get {
                return ResourceManager.GetString("Settings_Version_GitCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Date:.
        /// </summary>
        public static string Settings_Version_GitCommitDate {
            get {
                return ResourceManager.GetString("Settings_Version_GitCommitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informational Version:.
        /// </summary>
        public static string Settings_Version_Informational {
            get {
                return ResourceManager.GetString("Settings_Version_Informational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Published:.
        /// </summary>
        public static string Settings_Version_LatestPublished {
            get {
                return ResourceManager.GetString("Settings_Version_LatestPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version:.
        /// </summary>
        public static string Settings_Version_LatestVersion {
            get {
                return ResourceManager.GetString("Settings_Version_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open AppCast.
        /// </summary>
        public static string Settings_Version_OpenAppCast {
            get {
                return ResourceManager.GetString("Settings_Version_OpenAppCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string Settings_Version_OpenReleaseNotes {
            get {
                return ResourceManager.GetString("Settings_Version_OpenReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Information.
        /// </summary>
        public static string Settings_Version_Title {
            get {
                return ResourceManager.GetString("Settings_Version_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your application up to date with the latest features and security improvements..
        /// </summary>
        public static string Settings_Version_UpdatesDescription {
            get {
                return ResourceManager.GetString("Settings_Version_UpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Details.
        /// </summary>
        public static string Settings_VersionDetails_Title {
            get {
                return ResourceManager.GetString("Settings_VersionDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Settings_VersionTab {
            get {
                return ResourceManager.GetString("Settings_VersionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tool Call Message.
        /// </summary>
        public static string ToolCall_DialogTitle {
            get {
                return ResourceManager.GetString("ToolCall_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tool call message content....
        /// </summary>
        public static string ToolCall_MessageWatermark {
            get {
                return ResourceManager.GetString("ToolCall_MessageWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tool.
        /// </summary>
        public static string Tools_AddTool {
            get {
                return ResourceManager.GetString("Tools_AddTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the tool: {0}.
        /// </summary>
        public static string Tools_AddToolError {
            get {
                return ResourceManager.GetString("Tools_AddToolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Tools.
        /// </summary>
        public static string Tools_AvailableTools {
            get {
                return ResourceManager.GetString("Tools_AvailableTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Tools_ClearAll {
            get {
                return ResourceManager.GetString("Tools_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all tools.
        /// </summary>
        public static string Tools_ClearAllToolTip {
            get {
                return ResourceManager.GetString("Tools_ClearAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tools panel.
        /// </summary>
        public static string Tools_ClosePanel {
            get {
                return ResourceManager.GetString("Tools_ClosePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error configuring &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Tools_ConfigError_Format {
            get {
                return ResourceManager.GetString("Tools_ConfigError_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general error occurred while showing tool configuration for &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Tools_ConfigGeneralError_Format {
            get {
                return ResourceManager.GetString("Tools_ConfigGeneralError_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration for &apos;{0}&apos; is not implemented by the plugin..
        /// </summary>
        public static string Tools_ConfigNotImplemented_Format {
            get {
                return ResourceManager.GetString("Tools_ConfigNotImplemented_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Tool.
        /// </summary>
        public static string Tools_ConfigureTool {
            get {
                return ResourceManager.GetString("Tools_ConfigureTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tool.
        /// </summary>
        public static string Tools_ConfirmDeleteTool {
            get {
                return ResourceManager.GetString("Tools_ConfirmDeleteTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;? This action cannot be undone..
        /// </summary>
        public static string Tools_ConfirmDeleteToolMessage {
            get {
                return ResourceManager.GetString("Tools_ConfirmDeleteToolMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string Tools_DefaultPluginName {
            get {
                return ResourceManager.GetString("Tools_DefaultPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tool.
        /// </summary>
        public static string Tools_DeleteTool {
            get {
                return ResourceManager.GetString("Tools_DeleteTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tool Name.
        /// </summary>
        public static string Tools_EditNameDialogTitle {
            get {
                return ResourceManager.GetString("Tools_EditNameDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tool name.
        /// </summary>
        public static string Tools_EditToolNameTooltip {
            get {
                return ResourceManager.GetString("Tools_EditToolNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Not Available.
        /// </summary>
        public static string Tools_FeatureNotAvailable_Title {
            get {
                return ResourceManager.GetString("Tools_FeatureNotAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string Tools_Initializing {
            get {
                return ResourceManager.GetString("Tools_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools allow LLMs to perform additional tasks like searching the web, accessing files, or running code..
        /// </summary>
        public static string Tools_NoToolsDescription {
            get {
                return ResourceManager.GetString("Tools_NoToolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tools Configured.
        /// </summary>
        public static string Tools_NoToolsTitle {
            get {
                return ResourceManager.GetString("Tools_NoToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin for &apos;{0}&apos; (ID: {1}) not found..
        /// </summary>
        public static string Tools_PluginNotFound_Format {
            get {
                return ResourceManager.GetString("Tools_PluginNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Tools_SelectAll {
            get {
                return ResourceManager.GetString("Tools_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all tools.
        /// </summary>
        public static string Tools_SelectAllToolTip {
            get {
                return ResourceManager.GetString("Tools_SelectAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the tools that this person can use.
        /// </summary>
        public static string Tools_SelectToolsDescription {
            get {
                return ResourceManager.GetString("Tools_SelectToolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools_Title {
            get {
                return ResourceManager.GetString("Tools_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tool name.
        /// </summary>
        public static string Tools_ToolNameWatermark {
            get {
                return ResourceManager.GetString("Tools_ToolNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Selection.
        /// </summary>
        public static string Tools_ToolSelection {
            get {
                return ResourceManager.GetString("Tools_ToolSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Model ({0}).
        /// </summary>
        public static string Tools_UnknownModel {
            get {
                return ResourceManager.GetString("Tools_UnknownModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayIcon_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Main Window.
        /// </summary>
        public static string TrayIcon_OpenMainWindow {
            get {
                return ResourceManager.GetString("TrayIcon_OpenMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string Update_CheckForUpdates {
            get {
                return ResourceManager.GetString("Update_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string Update_CheckingForUpdates {
            get {
                return ResourceManager.GetString("Update_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        public static string Update_NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("Update_NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available: Version {0}.
        /// </summary>
        public static string Update_UpdateAvailable {
            get {
                return ResourceManager.GetString("Update_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates: {0}.
        /// </summary>
        public static string Update_UpdateCheckError {
            get {
                return ResourceManager.GetString("Update_UpdateCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Total.
        /// </summary>
        public static string Usage_AccumulatedTokens {
            get {
                return ResourceManager.GetString("Usage_AccumulatedTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Counts.
        /// </summary>
        public static string Usage_AdditionalCounts {
            get {
                return ResourceManager.GetString("Usage_AdditionalCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Round.
        /// </summary>
        public static string Usage_CurrentRoundTokens {
            get {
                return ResourceManager.GetString("Usage_CurrentRoundTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token usage is updated in real-time as you interact with the AI. This information helps you track your consumption and optimize your prompts..
        /// </summary>
        public static string Usage_Information {
            get {
                return ResourceManager.GetString("Usage_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Tokens.
        /// </summary>
        public static string Usage_InputTokens {
            get {
                return ResourceManager.GetString("Usage_InputTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Tokens.
        /// </summary>
        public static string Usage_OutputTokens {
            get {
                return ResourceManager.GetString("Usage_OutputTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens.
        /// </summary>
        public static string Usage_Tab {
            get {
                return ResourceManager.GetString("Usage_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Usage.
        /// </summary>
        public static string Usage_Title {
            get {
                return ResourceManager.GetString("Usage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tokens.
        /// </summary>
        public static string Usage_TotalTokens {
            get {
                return ResourceManager.GetString("Usage_TotalTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string Wizard_Title {
            get {
                return ResourceManager.GetString("Wizard_Title", resourceCulture);
            }
        }
    }
}
