//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamingTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NamingTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string AdvConfig_BasicInformation {
            get {
                return ResourceManager.GetString("AdvConfig_BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string AdvConfig_Export {
            get {
                return ResourceManager.GetString("AdvConfig_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export current configuration.
        /// </summary>
        public static string AdvConfig_Export_Tooltip {
            get {
                return ResourceManager.GetString("AdvConfig_Export_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string AdvConfig_Import {
            get {
                return ResourceManager.GetString("AdvConfig_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import configuration from file.
        /// </summary>
        public static string AdvConfig_Import_Tooltip {
            get {
                return ResourceManager.GetString("AdvConfig_Import_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Parameters.
        /// </summary>
        public static string AdvConfig_InputParameters {
            get {
                return ResourceManager.GetString("AdvConfig_InputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Parameters.
        /// </summary>
        public static string AdvConfig_OutputParameters {
            get {
                return ResourceManager.GetString("AdvConfig_OutputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Config.
        /// </summary>
        public static string AdvConfig_ParallelConfig {
            get {
                return ResourceManager.GetString("AdvConfig_ParallelConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt Template.
        /// </summary>
        public static string AdvConfig_PromptTemplate {
            get {
                return ResourceManager.GetString("AdvConfig_PromptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string AdvConfig_SaveAndClose {
            get {
                return ResourceManager.GetString("AdvConfig_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and close.
        /// </summary>
        public static string AdvConfig_SaveAndClose_Tooltip {
            get {
                return ResourceManager.GetString("AdvConfig_SaveAndClose_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Mode.
        /// </summary>
        public static string AdvConfig_SimpleMode {
            get {
                return ResourceManager.GetString("AdvConfig_SimpleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to simple configuration mode.
        /// </summary>
        public static string AdvConfig_SimpleMode_Tooltip {
            get {
                return ResourceManager.GetString("AdvConfig_SimpleMode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available people:.
        /// </summary>
        public static string AvailableAssistants {
            get {
                return ResourceManager.GetString("AvailableAssistants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe what this function does....
        /// </summary>
        public static string BaseInfo_Description_Watermark {
            get {
                return ResourceManager.GetString("BaseInfo_Description_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a display name for this tool instance....
        /// </summary>
        public static string BaseInfo_DisplayName_Watermark {
            get {
                return ResourceManager.GetString("BaseInfo_DisplayName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only lowercase letters and underscores (e.g., create_subtask).
        /// </summary>
        public static string BaseInfo_SubtaskName_Watermark {
            get {
                return ResourceManager.GetString("BaseInfo_SubtaskName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string Button_SaveAndClose {
            get {
                return ResourceManager.GetString("Button_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Information.
        /// </summary>
        public static string Config_AddInformation {
            get {
                return ResourceManager.GetString("Config_AddInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Response Item.
        /// </summary>
        public static string Config_AddResponseItem {
            get {
                return ResourceManager.GetString("Config_AddResponseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Mode.
        /// </summary>
        public static string Config_AdvancedMode {
            get {
                return ResourceManager.GetString("Config_AdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to advanced configuration mode.
        /// </summary>
        public static string Config_AdvancedMode_Tooltip {
            get {
                return ResourceManager.GetString("Config_AdvancedMode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe what this subtask does.
        /// </summary>
        public static string Config_Description_Watermark {
            get {
                return ResourceManager.GetString("Config_Description_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a display name for this tool....
        /// </summary>
        public static string Config_DisplayName_Watermark {
            get {
                return ResourceManager.GetString("Config_DisplayName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings to JSON file.
        /// </summary>
        public static string Config_Export_Tooltip {
            get {
                return ResourceManager.GetString("Config_Export_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings from JSON file.
        /// </summary>
        public static string Config_Import_Tooltip {
            get {
                return ResourceManager.GetString("Config_Import_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information description.
        /// </summary>
        public static string Config_InformationDescription_Watermark {
            get {
                return ResourceManager.GetString("Config_InformationDescription_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information name.
        /// </summary>
        public static string Config_InformationName_Watermark {
            get {
                return ResourceManager.GetString("Config_InformationName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt Message.
        /// </summary>
        public static string Config_PromptMessage_Header {
            get {
                return ResourceManager.GetString("Config_PromptMessage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the prompt message for the subtask. Reference required information using double brackets, e.g., {{task}}, {{background}}, {{requirements}}..
        /// </summary>
        public static string Config_PromptMessage_Watermark {
            get {
                return ResourceManager.GetString("Config_PromptMessage_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this item.
        /// </summary>
        public static string Config_RemoveItem_Tooltip {
            get {
                return ResourceManager.GetString("Config_RemoveItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Information.
        /// </summary>
        public static string Config_RequiredInformation_Header {
            get {
                return ResourceManager.GetString("Config_RequiredInformation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the required information to be provided.
        /// </summary>
        public static string Config_RequiredInformationDescription_Watermark {
            get {
                return ResourceManager.GetString("Config_RequiredInformationDescription_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required information name.
        /// </summary>
        public static string Config_RequiredInformationName_Watermark {
            get {
                return ResourceManager.GetString("Config_RequiredInformationName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Add Response Item&apos; to specify the required information that the subtask must report back. These items define the structured data that the executive person must provide upon task completion..
        /// </summary>
        public static string Config_RequiredResponseItems_Description {
            get {
                return ResourceManager.GetString("Config_RequiredResponseItems_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Response Items.
        /// </summary>
        public static string Config_RequiredResponseItems_Header {
            get {
                return ResourceManager.GetString("Config_RequiredResponseItems_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Config_Separator {
            get {
                return ResourceManager.GetString("Config_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtask name must contain only lowercase letters (a-z) and underscores (_). No spaces, numbers, or uppercase letters allowed..
        /// </summary>
        public static string Config_SubtaskName_Tooltip {
            get {
                return ResourceManager.GetString("Config_SubtaskName_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only lowercase letters and underscores (e.g., create_subtask).
        /// </summary>
        public static string Config_SubtaskName_Watermark {
            get {
                return ResourceManager.GetString("Config_SubtaskName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        public static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause and wait.
        /// </summary>
        public static string DanglingBehavior_Pause {
            get {
                return ResourceManager.GetString("DanglingBehavior_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report error.
        /// </summary>
        public static string DanglingBehavior_ReportError {
            get {
                return ResourceManager.GetString("DanglingBehavior_ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urge (send reminders).
        /// </summary>
        public static string DanglingBehavior_Urge {
            get {
                return ResourceManager.GetString("DanglingBehavior_Urge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrarily redefining a concept and acting on the new definition.
        /// </summary>
        public static string DelegateSubtasks {
            get {
                return ResourceManager.GetString("DelegateSubtasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating recursion level.
        /// </summary>
        public static string Error_CalculatingRecursionLevel {
            get {
                return ResourceManager.GetString("Error_CalculatingRecursionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child session failed to provide a result after {0} attempts..
        /// </summary>
        public static string Error_ChildSessionFailedResult {
            get {
                return ResourceManager.GetString("Error_ChildSessionFailedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child session failed to provide a result after {0} attempts..
        /// </summary>
        public static string Error_ChildSessionTimeout {
            get {
                return ResourceManager.GetString("Error_ChildSessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host must be set before creating plugin instances.
        /// </summary>
        public static string Error_HostMustBeSet {
            get {
                return ResourceManager.GetString("Error_HostMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid recursion level configuration. Maximum level cannot be negative..
        /// </summary>
        public static string Error_InvalidRecursionLevel {
            get {
                return ResourceManager.GetString("Error_InvalidRecursionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameters: {0}.
        /// </summary>
        public static string Error_MissingRequiredParameters {
            get {
                return ResourceManager.GetString("Error_MissingRequiredParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} sessions completed successfully, {2} failed.
        /// </summary>
        public static string Error_ParallelExecutionDetails {
            get {
                return ResourceManager.GetString("Error_ParallelExecutionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error showing dialog.
        /// </summary>
        public static string Error_ShowingDialog {
            get {
                return ResourceManager.GetString("Error_ShowingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error in WaitChildSessionAsync.
        /// </summary>
        public static string Error_UnhandledInWaitChildSession {
            get {
                return ResourceManager.GetString("Error_UnhandledInWaitChildSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: None of the configured people ({0}) are currently available..
        /// </summary>
        public static string ErrorConfiguredAssistantsNotAvailable {
            get {
                return ResourceManager.GetString("ErrorConfiguredAssistantsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what happens when a child session fails to call the return tool..
        /// </summary>
        public static string ErrorHandling_BehaviorDescription {
            get {
                return ResourceManager.GetString("ErrorHandling_BehaviorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When return tool is not called:.
        /// </summary>
        public static string ErrorHandling_BehaviorLabel {
            get {
                return ResourceManager.GetString("ErrorHandling_BehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child session failed to call the return tool.
        /// </summary>
        public static string ErrorHandling_DefaultErrorMessage {
            get {
                return ResourceManager.GetString("ErrorHandling_DefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If left blank, a default error message will be used..
        /// </summary>
        public static string ErrorHandling_ErrorMessageHint {
            get {
                return ResourceManager.GetString("ErrorHandling_ErrorMessageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message:.
        /// </summary>
        public static string ErrorHandling_ErrorMessageLabel {
            get {
                return ResourceManager.GetString("ErrorHandling_ErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom error message....
        /// </summary>
        public static string ErrorHandling_ErrorMessagePlaceholder {
            get {
                return ResourceManager.GetString("ErrorHandling_ErrorMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend the workflow and wait for a human decision..
        /// </summary>
        public static string ErrorHandling_Info_PauseDescription {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_PauseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this when oversight is required before continuing..
        /// </summary>
        public static string ErrorHandling_Info_PauseNote {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_PauseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause for manual intervention.
        /// </summary>
        public static string ErrorHandling_Info_PauseTitle {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_PauseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow will remain paused until someone takes action..
        /// </summary>
        public static string ErrorHandling_Info_PauseWarning {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_PauseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop waiting and report an error back to the parent session right away..
        /// </summary>
        public static string ErrorHandling_Info_ReportErrorDescription {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_ReportErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a clear message so the parent session understands what went wrong..
        /// </summary>
        public static string ErrorHandling_Info_ReportErrorNote {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_ReportErrorNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report error immediately.
        /// </summary>
        public static string ErrorHandling_Info_ReportErrorTitle {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_ReportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send up to three reminders and give the child session more time to finish..
        /// </summary>
        public static string ErrorHandling_Info_UrgeDescription {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_UrgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the child session still does not respond, it will be marked as failed..
        /// </summary>
        public static string ErrorHandling_Info_UrgeNote {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_UrgeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urge child session.
        /// </summary>
        public static string ErrorHandling_Info_UrgeTitle {
            get {
                return ResourceManager.GetString("ErrorHandling_Info_UrgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure how child sessions handle errors and return tool behavior..
        /// </summary>
        public static string ErrorHandling_TabDescription {
            get {
                return ResourceManager.GetString("ErrorHandling_TabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Handling.
        /// </summary>
        public static string ErrorHandling_TabTitle {
            get {
                return ResourceManager.GetString("ErrorHandling_TabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urging Message:.
        /// </summary>
        public static string ErrorHandling_UrgingMessage {
            get {
                return ResourceManager.GetString("ErrorHandling_UrgingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message will be sent to prompt completion when the task is taking too long..
        /// </summary>
        public static string ErrorHandling_UrgingMessage_Hint {
            get {
                return ResourceManager.GetString("ErrorHandling_UrgingMessage_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to show when waiting for completion (optional)....
        /// </summary>
        public static string ErrorHandling_UrgingMessage_Watermark {
            get {
                return ResourceManager.GetString("ErrorHandling_UrgingMessage_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Maximum delegation level ({0}) reached. Current level: {1}. Further delegation not allowed..
        /// </summary>
        public static string ErrorMaxRecursionLevelReached {
            get {
                return ResourceManager.GetString("ErrorMaxRecursionLevelReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No people are available in the system..
        /// </summary>
        public static string ErrorNoAssistantsAvailable {
            get {
                return ResourceManager.GetString("ErrorNoAssistantsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No people are configured for subtask delegation. Please configure the tool to allow specific people..
        /// </summary>
        public static string ErrorNoAssistantsConfigured {
            get {
                return ResourceManager.GetString("ErrorNoAssistantsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No valid parameters found for parallel execution..
        /// </summary>
        public static string ErrorNoValidParametersForParallelExecution {
            get {
                return ResourceManager.GetString("ErrorNoValidParametersForParallelExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during parallel execution: {0}.
        /// </summary>
        public static string ErrorParallelExecution {
            get {
                return ResourceManager.GetString("ErrorParallelExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parameter.
        /// </summary>
        public static string ErrorReporting_AddParameter {
            get {
                return ResourceManager.GetString("ErrorReporting_AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause workflow.
        /// </summary>
        public static string ErrorReporting_Behavior_Pause {
            get {
                return ResourceManager.GetString("ErrorReporting_Behavior_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause the parent session and require manual intervention when LLM reports an error..
        /// </summary>
        public static string ErrorReporting_Behavior_PauseDescription {
            get {
                return ResourceManager.GetString("ErrorReporting_Behavior_PauseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report error.
        /// </summary>
        public static string ErrorReporting_Behavior_ReportError {
            get {
                return ResourceManager.GetString("ErrorReporting_Behavior_ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propagate the LLM-reported error to the parent session immediately..
        /// </summary>
        public static string ErrorReporting_Behavior_ReportErrorDescription {
            get {
                return ResourceManager.GetString("ErrorReporting_Behavior_ReportErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When LLM actively reports an error via tool call:.
        /// </summary>
        public static string ErrorReporting_BehaviorLabel {
            get {
                return ResourceManager.GetString("ErrorReporting_BehaviorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ErrorReporting_ClearAll {
            get {
                return ResourceManager.GetString("ErrorReporting_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom message to parent session:.
        /// </summary>
        public static string ErrorReporting_CustomParentMessageLabel {
            get {
                return ResourceManager.GetString("ErrorReporting_CustomParentMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the message that will be sent back to the parent session....
        /// </summary>
        public static string ErrorReporting_CustomParentMessagePlaceholder {
            get {
                return ResourceManager.GetString("ErrorReporting_CustomParentMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A detailed message describing what went wrong..
        /// </summary>
        public static string ErrorReporting_DefaultParameter_ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorReporting_DefaultParameter_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category or type of error that occurred..
        /// </summary>
        public static string ErrorReporting_DefaultParameter_ErrorType {
            get {
                return ResourceManager.GetString("ErrorReporting_DefaultParameter_ErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe this parameter.
        /// </summary>
        public static string ErrorReporting_DefaultParameterDescription {
            get {
                return ResourceManager.GetString("ErrorReporting_DefaultParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A child session&apos;s LLM actively reported an error..
        /// </summary>
        public static string ErrorReporting_DefaultParentMessage {
            get {
                return ResourceManager.GetString("ErrorReporting_DefaultParentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report errors encountered in executing.
        /// </summary>
        public static string ErrorReporting_DefaultToolDescription {
            get {
                return ResourceManager.GetString("ErrorReporting_DefaultToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report_error.
        /// </summary>
        public static string ErrorReporting_DefaultToolName {
            get {
                return ResourceManager.GetString("ErrorReporting_DefaultToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, LLMs can actively report errors through a dedicated tool call..
        /// </summary>
        public static string ErrorReporting_EnableDescription {
            get {
                return ResourceManager.GetString("ErrorReporting_EnableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable LLM error reporting tool.
        /// </summary>
        public static string ErrorReporting_EnableLabel {
            get {
                return ResourceManager.GetString("ErrorReporting_EnableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ErrorReporting_EnableOff {
            get {
                return ResourceManager.GetString("ErrorReporting_EnableOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ErrorReporting_EnableOn {
            get {
                return ResourceManager.GetString("ErrorReporting_EnableOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold the parent session until the reported error is reviewed..
        /// </summary>
        public static string ErrorReporting_Info_PauseDescription {
            get {
                return ResourceManager.GetString("ErrorReporting_Info_PauseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause when error reported.
        /// </summary>
        public static string ErrorReporting_Info_PauseTitle {
            get {
                return ResourceManager.GetString("ErrorReporting_Info_PauseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send error details to the parent session and mark the workflow as failed..
        /// </summary>
        public static string ErrorReporting_Info_ReportErrorDescription {
            get {
                return ResourceManager.GetString("ErrorReporting_Info_ReportErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report error to parent.
        /// </summary>
        public static string ErrorReporting_Info_ReportErrorTitle {
            get {
                return ResourceManager.GetString("ErrorReporting_Info_ReportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load defaults.
        /// </summary>
        public static string ErrorReporting_LoadDefaults {
            get {
                return ResourceManager.GetString("ErrorReporting_LoadDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No LLM error reporting parameters.
        /// </summary>
        public static string ErrorReporting_NoParameters {
            get {
                return ResourceManager.GetString("ErrorReporting_NoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parameters to define the structured error data that LLMs can provide when reporting errors..
        /// </summary>
        public static string ErrorReporting_NoParametersDescription {
            get {
                return ResourceManager.GetString("ErrorReporting_NoParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reporting parameters.
        /// </summary>
        public static string ErrorReporting_ParametersHeader {
            get {
                return ResourceManager.GetString("ErrorReporting_ParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable LLMs to actively report errors using a dedicated tool (distinct from timeout handling)..
        /// </summary>
        public static string ErrorReporting_SectionDescription {
            get {
                return ResourceManager.GetString("ErrorReporting_SectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM Error Reporting Tool.
        /// </summary>
        public static string ErrorReporting_SectionTitle {
            get {
                return ResourceManager.GetString("ErrorReporting_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool description:.
        /// </summary>
        public static string ErrorReporting_ToolDescriptionLabel {
            get {
                return ResourceManager.GetString("ErrorReporting_ToolDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe what happens when the LLM calls this error reporting tool....
        /// </summary>
        public static string ErrorReporting_ToolDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ErrorReporting_ToolDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool name:.
        /// </summary>
        public static string ErrorReporting_ToolNameLabel {
            get {
                return ResourceManager.GetString("ErrorReporting_ToolNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., report_error.
        /// </summary>
        public static string ErrorReporting_ToolNamePlaceholder {
            get {
                return ResourceManager.GetString("ErrorReporting_ToolNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM error reporting parameters contain duplicates: {0}..
        /// </summary>
        public static string ErrorReporting_Validation_DuplicateParameters {
            get {
                return ResourceManager.GetString("ErrorReporting_Validation_DuplicateParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM error reporting parameters must have non-empty names..
        /// </summary>
        public static string ErrorReporting_Validation_InvalidParameterName {
            get {
                return ResourceManager.GetString("ErrorReporting_Validation_InvalidParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM error reporting tool name must be different from the return tool name..
        /// </summary>
        public static string ErrorReporting_Validation_ToolNameConflict {
            get {
                return ResourceManager.GetString("ErrorReporting_Validation_ToolNameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM error reporting tool name is required when error reporting is enabled..
        /// </summary>
        public static string ErrorReporting_Validation_ToolNameRequired {
            get {
                return ResourceManager.GetString("ErrorReporting_Validation_ToolNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The specified person &apos;{0}&apos; is either not available or not configured. Available people: {1}.
        /// </summary>
        public static string ErrorSpecifiedAssistantNotAvailable {
            get {
                return ResourceManager.GetString("ErrorSpecifiedAssistantNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error delegating subtask: {0}.
        /// </summary>
        public static string ErrorStartingHelpSession {
            get {
                return ResourceManager.GetString("ErrorStartingHelpSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Subtask description is required..
        /// </summary>
        public static string ErrorSubtaskEmpty {
            get {
                return ResourceManager.GetString("ErrorSubtaskEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Field_Description {
            get {
                return ResourceManager.GetString("Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Field_DisplayName {
            get {
                return ResourceManager.GetString("Field_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Person:.
        /// </summary>
        public static string Field_ExecutivePerson {
            get {
                return ResourceManager.GetString("Field_ExecutivePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a person.
        /// </summary>
        public static string Field_ExecutivePerson_Placeholder {
            get {
                return ResourceManager.GetString("Field_ExecutivePerson_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Current Session Person.
        /// </summary>
        public static string Field_ExecutivePerson_UseCurrentSession {
            get {
                return ResourceManager.GetString("Field_ExecutivePerson_UseCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate to the person from the active session.
        /// </summary>
        public static string Field_ExecutivePerson_UseCurrentSession_Description {
            get {
                return ResourceManager.GetString("Field_ExecutivePerson_UseCurrentSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Recursion Level:.
        /// </summary>
        public static string Field_MaxRecursionLevel {
            get {
                return ResourceManager.GetString("Field_MaxRecursionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Field_Name {
            get {
                return ResourceManager.GetString("Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Field_Required {
            get {
                return ResourceManager.GetString("Field_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtask Description:.
        /// </summary>
        public static string Field_SubtaskDescription {
            get {
                return ResourceManager.GetString("Field_SubtaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtask Name:.
        /// </summary>
        public static string Field_SubtaskName {
            get {
                return ResourceManager.GetString("Field_SubtaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtask name must contain only lowercase letters and underscores.
        /// </summary>
        public static string Field_SubtaskName_Validation {
            get {
                return ResourceManager.GetString("Field_SubtaskName_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtask delegated to {0}: {1}.
        /// </summary>
        public static string HelpSessionStarted {
            get {
                return ResourceManager.GetString("HelpSessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add First Parameter.
        /// </summary>
        public static string InputParams_AddFirstParameter {
            get {
                return ResourceManager.GetString("InputParams_AddFirstParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parameter.
        /// </summary>
        public static string InputParams_AddParameter {
            get {
                return ResourceManager.GetString("InputParams_AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new input parameter.
        /// </summary>
        public static string InputParams_AddParameter_Tooltip {
            get {
                return ResourceManager.GetString("InputParams_AddParameter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string InputParams_ClearAll {
            get {
                return ResourceManager.GetString("InputParams_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all parameters.
        /// </summary>
        public static string InputParams_ClearAll_Tooltip {
            get {
                return ResourceManager.GetString("InputParams_ClearAll_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Parameters.
        /// </summary>
        public static string InputParams_Header {
            get {
                return ResourceManager.GetString("InputParams_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Parameters Configured.
        /// </summary>
        public static string InputParams_NoParameters {
            get {
                return ResourceManager.GetString("InputParams_NoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add input parameters to define the data your tool accepts.
        /// </summary>
        public static string InputParams_NoParameters_Description {
            get {
                return ResourceManager.GetString("InputParams_NoParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child session {0} completed. Success: {1}.
        /// </summary>
        public static string Log_ChildSessionCompleted {
            get {
                return ResourceManager.GetString("Log_ChildSessionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child session {0} ended due to timeout/cancellation.
        /// </summary>
        public static string Log_ChildSessionTimeout {
            get {
                return ResourceManager.GetString("Log_ChildSessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomReturnResultTool registered for child session {0}.
        /// </summary>
        public static string Log_CustomReturnToolRegistered {
            get {
                return ResourceManager.GetString("Log_CustomReturnToolRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result not provided yet – retry {0}/{1}.
        /// </summary>
        public static string Log_ResultNotProvided {
            get {
                return ResourceManager.GetString("Log_ResultNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending initial message to child session {0}.
        /// </summary>
        public static string Log_SendingInitialMessage {
            get {
                return ResourceManager.GetString("Log_SendingInitialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Delegation Level.
        /// </summary>
        public static string MaxRecursionLevel {
            get {
                return ResourceManager.GetString("MaxRecursionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please finalize your task by submitting your results ONLY through the {{_Config.ReturnToolName}} tool. Do not respond with additional conversation or explanations. When invoking the {{_Config.ReturnToolName}} tool, ensure all required parameters are included along with any relevant data..
        /// </summary>
        public static string Message_FinalizeTaskReminder {
            get {
                return ResourceManager.GetString("Message_FinalizeTaskReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming Tool - Configuration.
        /// </summary>
        public static string NamingConfiguration {
            get {
                return ResourceManager.GetString("NamingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming Tool.
        /// </summary>
        public static string NamingDisplayName {
            get {
                return ResourceManager.GetString("NamingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a subtask or a function call..
        /// </summary>
        public static string NamingFunctionDescription {
            get {
                return ResourceManager.GetString("NamingFunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No people are currently available..
        /// </summary>
        public static string NoAIAssistantsAvailable {
            get {
                return ResourceManager.GetString("NoAIAssistantsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string OutputParams_ClearAll {
            get {
                return ResourceManager.GetString("OutputParams_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all parameters.
        /// </summary>
        public static string OutputParams_ClearAll_Tooltip {
            get {
                return ResourceManager.GetString("OutputParams_ClearAll_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Parameters.
        /// </summary>
        public static string OutputParams_Header {
            get {
                return ResourceManager.GetString("OutputParams_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Return Parameters Configured.
        /// </summary>
        public static string OutputParams_NoParameters {
            get {
                return ResourceManager.GetString("OutputParams_NoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure return parameters to define the data your tool returns.
        /// </summary>
        public static string OutputParams_NoParameters_Description {
            get {
                return ResourceManager.GetString("OutputParams_NoParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Parameters.
        /// </summary>
        public static string OutputParams_ReturnParameters {
            get {
                return ResourceManager.GetString("OutputParams_ReturnParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe what this tool does....
        /// </summary>
        public static string OutputParams_ToolDescription_Watermark {
            get {
                return ResourceManager.GetString("OutputParams_ToolDescription_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Name:.
        /// </summary>
        public static string OutputParams_ToolName {
            get {
                return ResourceManager.GetString("OutputParams_ToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., set_result, complete_task.
        /// </summary>
        public static string OutputParams_ToolName_Watermark {
            get {
                return ResourceManager.GetString("OutputParams_ToolName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urging Message:.
        /// </summary>
        public static string OutputParams_UrgingMessage {
            get {
                return ResourceManager.GetString("OutputParams_UrgingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to show when waiting for completion (optional)....
        /// </summary>
        public static string OutputParams_UrgingMessage_Watermark {
            get {
                return ResourceManager.GetString("OutputParams_UrgingMessage_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ParallelConfig_Add {
            get {
                return ResourceManager.GetString("ParallelConfig_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure basic parallel execution parameters.
        /// </summary>
        public static string ParallelConfig_BasicSettings_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_BasicSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        public static string ParallelConfig_BasicSettings_Header {
            get {
                return ResourceManager.GetString("ParallelConfig_BasicSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Parameters.
        /// </summary>
        public static string ParallelConfig_EnterParameters {
            get {
                return ResourceManager.GetString("ParallelConfig_EnterParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter parameters directly, one per line..
        /// </summary>
        public static string ParallelConfig_EnterParameters_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_EnterParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter each parameter on a new line....
        /// </summary>
        public static string ParallelConfig_EnterParameters_Watermark {
            get {
                return ResourceManager.GetString("ParallelConfig_EnterParameters_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Parameters.
        /// </summary>
        public static string ParallelConfig_ExcludedParameters {
            get {
                return ResourceManager.GetString("ParallelConfig_ExcludedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parameters to exclude from parameter-based parallel execution.
        /// </summary>
        public static string ParallelConfig_ExcludedParameters_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_ExcludedParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Parameters:.
        /// </summary>
        public static string ParallelConfig_ExcludedParameters_Label {
            get {
                return ResourceManager.GetString("ParallelConfig_ExcludedParameters_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how parallel execution should be handled.
        /// </summary>
        public static string ParallelConfig_ExecutionType_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_ExecutionType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External List - Use custom string list.
        /// </summary>
        public static string ParallelConfig_ExecutionType_ExternalList {
            get {
                return ResourceManager.GetString("ParallelConfig_ExecutionType_ExternalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Type.
        /// </summary>
        public static string ParallelConfig_ExecutionType_Header {
            get {
                return ResourceManager.GetString("ParallelConfig_ExecutionType_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Based - Use specific array/list parameter.
        /// </summary>
        public static string ParallelConfig_ExecutionType_ListBased {
            get {
                return ResourceManager.GetString("ParallelConfig_ExecutionType_ListBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None - No parallel execution.
        /// </summary>
        public static string ParallelConfig_ExecutionType_None {
            get {
                return ResourceManager.GetString("ParallelConfig_ExecutionType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Based - Use POCO parameters.
        /// </summary>
        public static string ParallelConfig_ExecutionType_ParameterBased {
            get {
                return ResourceManager.GetString("ParallelConfig_ExecutionType_ParameterBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the external list of items for parallel processing.
        /// </summary>
        public static string ParallelConfig_ExternalList_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_ExternalList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External List Configuration.
        /// </summary>
        public static string ParallelConfig_ExternalList_Header {
            get {
                return ResourceManager.GetString("ParallelConfig_ExternalList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure input parameters for parallel execution.
        /// </summary>
        public static string ParallelConfig_InputParametersBased_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_InputParametersBased_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Parameters Based Settings.
        /// </summary>
        public static string ParallelConfig_InputParametersBased_Header {
            get {
                return ResourceManager.GetString("ParallelConfig_InputParametersBased_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the parameter that contains the list for parallel processing.
        /// </summary>
        public static string ParallelConfig_ListParameter_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_ListParameter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Parameter Configuration.
        /// </summary>
        public static string ParallelConfig_ListParameter_Header {
            get {
                return ResourceManager.GetString("ParallelConfig_ListParameter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Concurrency.
        /// </summary>
        public static string ParallelConfig_MaxConcurrency {
            get {
                return ResourceManager.GetString("ParallelConfig_MaxConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parallel sessions to run simultaneously.
        /// </summary>
        public static string ParallelConfig_MaxConcurrency_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_MaxConcurrency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of concurrent sessions (must be &gt; 0).
        /// </summary>
        public static string ParallelConfig_MaxConcurrency_Tooltip {
            get {
                return ResourceManager.GetString("ParallelConfig_MaxConcurrency_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Strategy.
        /// </summary>
        public static string ParallelConfig_ResultStrategy {
            get {
                return ResourceManager.GetString("ParallelConfig_ResultStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to handle results from parallel sessions.
        /// </summary>
        public static string ParallelConfig_ResultStrategy_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_ResultStrategy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select List Parameter.
        /// </summary>
        public static string ParallelConfig_SelectListParameter {
            get {
                return ResourceManager.GetString("ParallelConfig_SelectListParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an array parameter from your input parameters to use for parallel processing.
        /// </summary>
        public static string ParallelConfig_SelectListParameter_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_SelectListParameter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an array parameter....
        /// </summary>
        public static string ParallelConfig_SelectListParameter_Placeholder {
            get {
                return ResourceManager.GetString("ParallelConfig_SelectListParameter_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a parameter....
        /// </summary>
        public static string ParallelConfig_SelectParameter_Placeholder {
            get {
                return ResourceManager.GetString("ParallelConfig_SelectParameter_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timeout.
        /// </summary>
        public static string ParallelConfig_SessionTimeout {
            get {
                return ResourceManager.GetString("ParallelConfig_SessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum time to wait for each parallel session.
        /// </summary>
        public static string ParallelConfig_SessionTimeout_Description {
            get {
                return ResourceManager.GetString("ParallelConfig_SessionTimeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt Template.
        /// </summary>
        public static string PromptTemplate_Header {
            get {
                return ResourceManager.GetString("PromptTemplate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Parameters.
        /// </summary>
        public static string PromptTemplate_InsertParameters {
            get {
                return ResourceManager.GetString("PromptTemplate_InsertParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert input parameters into template.
        /// </summary>
        public static string PromptTemplate_InsertParameters_Tooltip {
            get {
                return ResourceManager.GetString("PromptTemplate_InsertParameters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your prompt template here. Use {{parameter}} syntax for placeholders....
        /// </summary>
        public static string PromptTemplate_Watermark {
            get {
                return ResourceManager.GetString("PromptTemplate_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        public static string Section_BasicSettings {
            get {
                return ResourceManager.GetString("Section_BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the prompt message that will be sent to the executive person:.
        /// </summary>
        public static string Section_PromptMessage_Description {
            get {
                return ResourceManager.GetString("Section_PromptMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure required information that provides background context and task details:.
        /// </summary>
        public static string Section_RequiredInformation_Description {
            get {
                return ResourceManager.GetString("Section_RequiredInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No required information configured.
        /// </summary>
        public static string Section_RequiredInformation_Empty {
            get {
                return ResourceManager.GetString("Section_RequiredInformation_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Add Information&apos; to define information that provides background context, task details, and other data needed for the subtask execution..
        /// </summary>
        public static string Section_RequiredInformation_EmptyDescription {
            get {
                return ResourceManager.GetString("Section_RequiredInformation_EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the required information items that the subtask must report back upon completion:.
        /// </summary>
        public static string Section_ReturnParameters_Description {
            get {
                return ResourceManager.GetString("Section_ReturnParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No required response items configured.
        /// </summary>
        public static string Section_ReturnParameters_Empty {
            get {
                return ResourceManager.GetString("Section_ReturnParameters_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Add Response Item&apos; to specify the required information that the subtask must report back. These items define the structured data that the executive person must provide upon task completion..
        /// </summary>
        public static string Section_ReturnParameters_EmptyDescription {
            get {
                return ResourceManager.GetString("Section_ReturnParameters_EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select People for Subtasks.
        /// </summary>
        public static string SelectAIAssistants {
            get {
                return ResourceManager.GetString("SelectAIAssistants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which people should be available for subtask delegation..
        /// </summary>
        public static string SelectAIAssistantsDescription {
            get {
                return ResourceManager.GetString("SelectAIAssistantsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Status_Failed {
            get {
                return ResourceManager.GetString("Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result available.
        /// </summary>
        public static string Status_NoResult {
            get {
                return ResourceManager.GetString("Status_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results available.
        /// </summary>
        public static string Status_NoResults {
            get {
                return ResourceManager.GetString("Status_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No successful results available.
        /// </summary>
        public static string Status_NoSuccessfulResults {
            get {
                return ResourceManager.GetString("Status_NoSuccessfulResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel execution failed: {0}.
        /// </summary>
        public static string Status_ParallelFailed {
            get {
                return ResourceManager.GetString("Status_ParallelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel execution completed with first result: {0}.
        /// </summary>
        public static string Status_ParallelFirstWinsCompleted {
            get {
                return ResourceManager.GetString("Status_ParallelFirstWinsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel execution completed with streaming results: {0}/{1} sessions succeeded.
        /// </summary>
        public static string Status_ParallelStreamingCompleted {
            get {
                return ResourceManager.GetString("Status_ParallelStreamingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel execution completed: {0}/{1} sessions succeeded. Results:{2}.
        /// </summary>
        public static string Status_ParallelWaitForAllCompleted {
            get {
                return ResourceManager.GetString("Status_ParallelWaitForAllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string Status_Succeeded {
            get {
                return ResourceManager.GetString("Status_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming Configuration.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
