//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrowserTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrowserTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Path.
        /// </summary>
        public static string BrowserPath {
            get {
                return ResourceManager.GetString("BrowserPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter browser executable path....
        /// </summary>
        public static string BrowserPathPlaceholder {
            get {
                return ResourceManager.GetString("BrowserPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Settings.
        /// </summary>
        public static string BrowserSettings {
            get {
                return ResourceManager.GetString("BrowserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your browser tool settings and preferences.
        /// </summary>
        public static string BrowserSettings_Description {
            get {
                return ResourceManager.GetString("BrowserSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web browser tool.
        /// </summary>
        public static string BrowserToolDescription {
            get {
                return ResourceManager.GetString("BrowserToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Tool.
        /// </summary>
        public static string BrowserToolDisplayName {
            get {
                return ResourceManager.GetString("BrowserToolDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Tool Type.
        /// </summary>
        public static string BrowserToolType {
            get {
                return ResourceManager.GetString("BrowserToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Type.
        /// </summary>
        public static string BrowserType {
            get {
                return ResourceManager.GetString("BrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        public static string Button_NewTab {
            get {
                return ResourceManager.GetString("Button_NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded.
        /// </summary>
        public static string Embedded {
            get {
                return ResourceManager.GetString("Embedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser window is null.
        /// </summary>
        public static string Error_BrowserWindowNull {
            get {
                return ResourceManager.GetString("Error_BrowserWindowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} control.
        /// </summary>
        public static string Error_ControlNotFound {
            get {
                return ResourceManager.GetString("Error_ControlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating PDF: {0}.
        /// </summary>
        public static string Error_GeneratingPDF {
            get {
                return ResourceManager.GetString("Error_GeneratingPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please get page content first..
        /// </summary>
        public static string Error_GetPageContentFirst {
            get {
                return ResourceManager.GetString("Error_GetPageContentFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No web page is currently open. Please use the browser_open_web_url function first to navigate to a webpage..
        /// </summary>
        public static string Error_NoWebPageOpen {
            get {
                return ResourceManager.GetString("Error_NoWebPageOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing DOM: {0}.
        /// </summary>
        public static string Error_ProcessingDOM {
            get {
                return ResourceManager.GetString("Error_ProcessingDOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing source: {0}.
        /// </summary>
        public static string Error_ProcessingSource {
            get {
                return ResourceManager.GetString("Error_ProcessingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving page source: {0}.
        /// </summary>
        public static string Error_RetrievingPageSource {
            get {
                return ResourceManager.GetString("Error_RetrievingPageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        public static string Error_ValidationFailed {
            get {
                return ResourceManager.GetString("Error_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files.
        /// </summary>
        public static string ExecutableFiles {
            get {
                return ResourceManager.GetString("ExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Field_DisplayName {
            get {
                return ResourceManager.GetString("Field_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active tab.
        /// </summary>
        public static string NoActiveTab {
            get {
                return ResourceManager.GetString("NoActiveTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaywrightLocal.
        /// </summary>
        public static string PlaywrightLocal {
            get {
                return ResourceManager.GetString("PlaywrightLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaywrightOS.
        /// </summary>
        public static string PlaywrightOS {
            get {
                return ResourceManager.GetString("PlaywrightOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        public static string Section_BasicSettings {
            get {
                return ResourceManager.GetString("Section_BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Configuration.
        /// </summary>
        public static string Section_BrowserConfiguration {
            get {
                return ResourceManager.GetString("Section_BrowserConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Browser Executable.
        /// </summary>
        public static string SelectBrowserExecutable {
            get {
                return ResourceManager.GetString("SelectBrowserExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each session operates its own browser tab, providing isolated browsing context.
        /// </summary>
        public static string SessionAware_Description {
            get {
                return ResourceManager.GetString("SessionAware_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable session-aware tab management.
        /// </summary>
        public static string SessionAware_Label {
            get {
                return ResourceManager.GetString("SessionAware_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ×.
        /// </summary>
        public static string Tab_Close {
            get {
                return ResourceManager.GetString("Tab_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        public static string Tab_DefaultTitle {
            get {
                return ResourceManager.GetString("Tab_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ToolTip_Back {
            get {
                return ResourceManager.GetString("ToolTip_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Tools.
        /// </summary>
        public static string ToolTip_DeveloperTools {
            get {
                return ResourceManager.GetString("ToolTip_DeveloperTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ToolTip_Forward {
            get {
                return ResourceManager.GetString("ToolTip_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        public static string ToolTip_NewTab {
            get {
                return ResourceManager.GetString("ToolTip_NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ToolTip_Refresh {
            get {
                return ResourceManager.GetString("ToolTip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or enter web address....
        /// </summary>
        public static string Watermark_AddressBar {
            get {
                return ResourceManager.GetString("Watermark_AddressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new tab to start browsing.
        /// </summary>
        public static string Welcome_Subtitle {
            get {
                return ResourceManager.GetString("Welcome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Browser Tool.
        /// </summary>
        public static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
    }
}
