//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaoStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API provider not found: {0}.
        /// </summary>
        internal static string Error_ApiProviderNotFound {
            get {
                return ResourceManager.GetString("Error_ApiProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message processing was aborted by a filter..
        /// </summary>
        internal static string Error_FilterAborted {
            get {
                return ResourceManager.GetString("Error_FilterAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Chat client: {0}.
        /// </summary>
        internal static string Error_InitializeChatClient {
            get {
                return ResourceManager.GetString("Error_InitializeChatClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error communicating with LLM service: {0}.
        /// </summary>
        internal static string Error_LlmCommunication {
            get {
                return ResourceManager.GetString("Error_LlmCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No persons available for provider.
        /// </summary>
        internal static string Error_NoPersonsAvailable {
            get {
                return ResourceManager.GetString("Error_NoPersonsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person not found: {0}.
        /// </summary>
        internal static string Error_PersonNotFound {
            get {
                return ResourceManager.GetString("Error_PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found.
        /// </summary>
        internal static string Error_SessionNotFound {
            get {
                return ResourceManager.GetString("Error_SessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported provider type: {0}.
        /// </summary>
        internal static string Error_UnsupportedProviderType {
            get {
                return ResourceManager.GetString("Error_UnsupportedProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message cannot be blank. Please enter text and try again..
        /// </summary>
        internal static string Error_UserMessageEmpty {
            get {
                return ResourceManager.GetString("Error_UserMessageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsession created.
        /// </summary>
        internal static string InformationMessage_SubsessionCreated {
            get {
                return ResourceManager.GetString("InformationMessage_SubsessionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool call: &apos;{0}&apos;, Arguments: {1}, ID: {2}.
        /// </summary>
        internal static string ToolCall_Content {
            get {
                return ResourceManager.GetString("ToolCall_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool call result: {0}, ID: {1}
        ///.
        /// </summary>
        internal static string ToolCall_Result {
            get {
                return ResourceManager.GetString("ToolCall_Result", resourceCulture);
            }
        }
    }
}
