//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure root directory for file operations. Access restricted to files within this directory..
        /// </summary>
        public static string Configuration_Description {
            get {
                return ResourceManager.GetString("Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Tool Configuration.
        /// </summary>
        public static string Configuration_Header {
            get {
                return ResourceManager.GetString("Configuration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected directory serves as root location. All file operations restricted to this directory..
        /// </summary>
        public static string Configuration_Info {
            get {
                return ResourceManager.GetString("Configuration_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is required for {0} operation.
        /// </summary>
        public static string Error_ContentRequired {
            get {
                return ResourceManager.GetString("Error_ContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying file: {0}.
        /// </summary>
        public static string Error_CopyingFile {
            get {
                return ResourceManager.GetString("Error_CopyingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating directory: {0}.
        /// </summary>
        public static string Error_CreatingDirectory {
            get {
                return ResourceManager.GetString("Error_CreatingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting directory: {0}.
        /// </summary>
        public static string Error_DeletingDirectory {
            get {
                return ResourceManager.GetString("Error_DeletingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file: {0}.
        /// </summary>
        public static string Error_DeletingFile {
            get {
                return ResourceManager.GetString("Error_DeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path is required for {0} operation.
        /// </summary>
        public static string Error_DestinationPathRequired {
            get {
                return ResourceManager.GetString("Error_DestinationPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found: {0}.
        /// </summary>
        public static string Error_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Error_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        public static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error performing file operation: {0}.
        /// </summary>
        public static string Error_FileOperation {
            get {
                return ResourceManager.GetString("Error_FileOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path cannot be null or empty.
        /// </summary>
        public static string Error_FilePathNull {
            get {
                return ResourceManager.GetString("Error_FilePathNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error performing folder operation: {0}.
        /// </summary>
        public static string Error_FolderOperation {
            get {
                return ResourceManager.GetString("Error_FolderOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error listing directory: {0}.
        /// </summary>
        public static string Error_ListingDirectory {
            get {
                return ResourceManager.GetString("Error_ListingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error moving file: {0}.
        /// </summary>
        public static string Error_MovingFile {
            get {
                return ResourceManager.GetString("Error_MovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation type cannot be null or empty.
        /// </summary>
        public static string Error_OperationTypeNull {
            get {
                return ResourceManager.GetString("Error_OperationTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file: {0}.
        /// </summary>
        public static string Error_ReadingFile {
            get {
                return ResourceManager.GetString("Error_ReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching files: {0}.
        /// </summary>
        public static string Error_SearchingFiles {
            get {
                return ResourceManager.GetString("Error_SearchingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search pattern is required for search operation.
        /// </summary>
        public static string Error_SearchPatternRequired {
            get {
                return ResourceManager.GetString("Error_SearchPatternRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file not found: {0}.
        /// </summary>
        public static string Error_SourceFileNotFound {
            get {
                return ResourceManager.GetString("Error_SourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start line and end line are required for apply_diff operation.
        /// </summary>
        public static string Error_StartEndLineRequired {
            get {
                return ResourceManager.GetString("Error_StartEndLineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operation type: {0}.
        /// </summary>
        public static string Error_UnknownOperationType {
            get {
                return ResourceManager.GetString("Error_UnknownOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} file: {1}.
        /// </summary>
        public static string Error_WritingFile {
            get {
                return ResourceManager.GetString("Error_WritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Directory.
        /// </summary>
        public static string Field_DefaultDirectory {
            get {
                return ResourceManager.GetString("Field_DefaultDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Field_DisplayName {
            get {
                return ResourceManager.GetString("Field_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string FileToolConfig_Browse {
            get {
                return ResourceManager.GetString("FileToolConfig_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FileToolConfig_Cancel {
            get {
                return ResourceManager.GetString("FileToolConfig_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Directory:.
        /// </summary>
        public static string FileToolConfig_CurrentDirectory {
            get {
                return ResourceManager.GetString("FileToolConfig_CurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Directory.
        /// </summary>
        public static string FileToolConfig_DefaultDirectory {
            get {
                return ResourceManager.GetString("FileToolConfig_DefaultDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select root directory for file operations. Access limited to files within this directory..
        /// </summary>
        public static string FileToolConfig_DefaultDirectoryDescription {
            get {
                return ResourceManager.GetString("FileToolConfig_DefaultDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Tool Configuration.
        /// </summary>
        public static string FileToolConfig_DialogTitle {
            get {
                return ResourceManager.GetString("FileToolConfig_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected directory serves as root location for file operations. Access restricted to files within this directory..
        /// </summary>
        public static string FileToolConfig_InfoText {
            get {
                return ResourceManager.GetString("FileToolConfig_InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileToolConfig_Save {
            get {
                return ResourceManager.GetString("FileToolConfig_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Root Directory.
        /// </summary>
        public static string FileToolConfig_SelectFolder {
            get {
                return ResourceManager.GetString("FileToolConfig_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appending to.
        /// </summary>
        public static string Operation_Appending {
            get {
                return ResourceManager.GetString("Operation_Appending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writing.
        /// </summary>
        public static string Operation_Writing {
            get {
                return ResourceManager.GetString("Operation_Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Tool Configuration.
        /// </summary>
        public static string Window_FileToolConfiguration_Title {
            get {
                return ResourceManager.GetString("Window_FileToolConfiguration_Title", resourceCulture);
            }
        }
    }
}
